# -------------------------------
# Example docker compose
# -------------------------------
services:
  jotall-bot:
    image: ghcr.io/tjallo/jotall-bot:0.2.1
    volumes:
      - ./tmp:/app/tmp
      - ./log:/app/log
      - ./data:/app/data
    ports:
      - 3000:3000
    environment:
      - APP_ID: "<YOUR_APP_ID>"
      - DISCORD_TOKEN: "<YOUR_DISCORD_TOKEN>"
      - PUBLIC_KEY: "<YOUR_PUBLIC_KEY>"
      - MINECRAFT_SERVER_SECRET="<YOUR_MINECRAFT_SERVER_SECRET>"
      - MINECRAFT_SERVER_IP="<YOUR_MINECRAFT_SERVER_IP>"
      - MINECRAFT_MGMT_SERVER_PORT="25565"
    restart: unless-stopped
